# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: backend
description: deploy myapp
serialPipeline:
 stages:
 - targetId: staging-env
   profiles: [staging]
 - targetId: prod-env
   profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: staging-env
description: Deploy api to staging
run:
 location: projects/jkwng-clouddeploy-stg-f112/locations/us-central1
executionConfigs:
- usages:
  - RENDER
  - DEPLOY
  serviceAccount: cloud-deploy-agent@jkwng-clouddeploy-ci-f112.iam.gserviceaccount.com
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prod-env
description: Deploy api to prod
requireApproval: true
run:
 location: projects/jkwng-clouddeploy-prd-f112/locations/us-central1
executionConfigs:
- usages:
  - RENDER
  - DEPLOY
  serviceAccount: cloud-deploy-agent@jkwng-clouddeploy-ci-f112.iam.gserviceaccount.com