apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend # this service will be created in Cloud Run via Skaffold
spec:
  template:
    spec:
      containers:
      - image: gcr.io/jkwng-images/cloud-run-backend